--- 
abstract: ACID transactions on a directory tree
author: 
  - Yuval Kogman <nothingmuch@woobling.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.003
license: mit
name: Directory-Transactional
requires: 
  Any::Moose: 0.07
  Data::Stream::Bulk: 0
  Data::UUID: 0
  Directory::Scratch: 0
  File::NFSLock: 0
  File::Path: 2.07
  Hash::Util::FieldHash::Compat: 0
  List::Util: 0
  Path::Class: 0
  Scope::Guard: 0
  Set::Object: 0
  Test::Exception: 0
  Test::TempDir: 0
  Test::use::ok: 0
  Time::HiRes: 0
  namespace::clean: 0
version: 0.08
